name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      env:
        USER: ${{ secrets.USER }}
        PASS: ${{ secrets.PASS }}
    
      run: |
          echo $USER
          echo $PASS 
          docker build . --file Dockerfile --tag sakshishukla235/github:latest
          docker login -u $USER -p $PASS
          docker push sakshishukla235/github:latest
